import { Book } from "../interfaces/User.interface";

export const myApi: Book[] = [
    {
      id: 1,
      bookTitle: 'El sonido del silencio',
      authors: 'Alex Campos',
      description: { publishedYear: 2005 },
      gender: 'Poesia',
      image: "https://picsum.photos/300/300?random=1",
      availabilityStatus: 'Exchange',
      price: 200,
    },
    {
      id: 2,
      bookTitle: 'Cien años de soledad',
      authors: 'Gabriel García M.',
      description: { publishedYear: 1967 },
      gender: 'Novela',
      image: "https://picsum.photos/300/300?random=2",
      availabilityStatus: 'Exchange',
      price: 350,
    },
    {
      id: 3,
      bookTitle: 'Don Quijote de la Mancha',
      authors: 'Miguel de Cervantes',
      description: { publishedYear: 1605 },
      gender: 'Novela',
      image: "https://picsum.photos/300/300?random=3",
      availabilityStatus: 'For sale',
      price: 500,
    },
    {
      id: 4,
      bookTitle: 'La sombra del viento',
      authors: 'Carlos Ruiz Z.',
      description: { publishedYear: 2001 },
      gender: 'Ficción',
      image: "https://picsum.photos/300/300?random=4",
      availabilityStatus: 'Exchange',
      price: 250,
    },
    {
      id: 5,
      bookTitle: 'El amor en tiempos..',
      authors: 'Gabriel García',
      description: { publishedYear: 1985 },
      gender: 'Novela',
      image: "https://picsum.photos/300/300?random=5",
      availabilityStatus: 'Exchange',
      price: 300,
    },
    {
      id: 6,
      bookTitle: 'Rayuela',
      authors: 'Julio Cortázar',
      description: { publishedYear: 1963 },
      gender: 'Novela',
      image: "https://picsum.photos/300/300?random=6",
      availabilityStatus: 'For sale',
      price: 280,
    },
    {
      id: 7,
      bookTitle: 'La casa de los espíritus',
      authors: 'Isabel Allende',
      description: { publishedYear: 1982 },
      gender: 'Ficción',
      image: "https://picsum.photos/300/300?random=7",
      availabilityStatus: 'Exchange',
      price: 220,
    },
    {
      id: 8,
      bookTitle: 'Pedro Páramo',
      authors: 'Juan Rulfo',
      description: { publishedYear: 1955 },
      gender: 'Novela',
      image: "https://picsum.photos/300/300?random=8",
      availabilityStatus: 'Exchange',
      price: 180,
    },
    {
      id: 9,
      bookTitle: 'La ciudad y los perros',
      authors: 'Mario Vargas Llosa',
      description: { publishedYear: 1963 },
      gender: 'Novela',
      image: "https://picsum.photos/300/300?random=9",
      availabilityStatus: 'For sale',
      price: 260,
    },
    {
      id: 10,
      bookTitle: 'La tregua',
      authors: 'Mario Benedetti',
      description: { publishedYear: 1960 },
      gender: 'Novela',
      image: "https://picsum.photos/300/300?random=10",
      availabilityStatus: 'Exchange',
      price: 190,
    },
    {
      id: 11,
      bookTitle: 'El túnel',
      authors: 'Ernesto Sabato',
      description: { publishedYear: 1948 },
      gender: 'Novela',
      image: "https://picsum.photos/300/300?random=11",
      availabilityStatus: 'Exchange',
      price: 210,
    },
    {
      id: 12,
      bookTitle: 'Fervor de Buenos Aires',
      authors: 'Jorge Luis Borges',
      description: { publishedYear: 1923 },
      gender: 'Poesia',
      image: "https://picsum.photos/300/300?random=12",
      availabilityStatus: 'For sale',
      price: 230,
    },
    {
      id: 13,
      bookTitle: 'Los detectives salvajes',
      authors: 'Roberto Bolaño',
      description: { publishedYear: 1998 },
      gender: 'Novela',
      image: "https://picsum.photos/300/300?random=13",
      availabilityStatus: 'Exchange',
      price: 320,
    },
    {
      id: 14,
      bookTitle: 'El Aleph',
      authors: 'Jorge Luis Borges',
      description: { publishedYear: 1949 },
      gender: 'Cuento',
      image: "https://picsum.photos/300/300?random=14",
      availabilityStatus: 'Exchange',
      price: 240,
    },
    {
      id: 15,
      bookTitle: 'Sobre héroes y tumbas',
      authors: 'Ernesto Sabato',
      description: { publishedYear: 1961 },
      gender: 'Novela',
      image: "https://picsum.photos/300/300?random=15",
      availabilityStatus: 'For sale',
      price: 290,
    }
  ];
  