import { Book } from "../interfaces/User.interface";

export const myApi: Book[] = [
  {
    id: 1,
    bookTitle: 'El sonido del silencio',
    authors: 'Alex Campos',
    description: { publishedYear: 2005 },
    gender: 'Poesía',
    image: "https://picsum.photos/300/300?random=1",
    availabilityStatus: 'Exchange',
    price: 200,
  },
  {
    id: 2,
    bookTitle: 'Cien años de soledad',
    authors: 'Gabriel García Márquez',
    description: { publishedYear: 1967 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=2",
    availabilityStatus: 'Exchange',
    price: 350,
  },
  {
    id: 3,
    bookTitle: 'Don Quijote de la Mancha',
    authors: 'Miguel de Cervantes',
    description: { publishedYear: 1605 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=3",
    availabilityStatus: 'For sale',
    price: 500,
  },
  {
    id: 4,
    bookTitle: 'La sombra del viento',
    authors: 'Carlos Ruiz Zafón',
    description: { publishedYear: 2001 },
    gender: 'Ficción',
    image: "https://picsum.photos/300/300?random=4",
    availabilityStatus: 'Exchange',
    price: 250,
  },
  {
    id: 5,
    bookTitle: 'El amor en los tiempos del cólera',
    authors: 'Gabriel García Márquez',
    description: { publishedYear: 1985 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=5",
    availabilityStatus: 'Exchange',
    price: 300,
  },
  {
    id: 6,
    bookTitle: 'Rayuela',
    authors: 'Julio Cortázar',
    description: { publishedYear: 1963 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=6",
    availabilityStatus: 'For sale',
    price: 280,
  },
  {
    id: 7,
    bookTitle: 'La casa de los espíritus',
    authors: 'Isabel Allende',
    description: { publishedYear: 1982 },
    gender: 'Ficción',
    image: "https://picsum.photos/300/300?random=7",
    availabilityStatus: 'Exchange',
    price: 220,
  },
  {
    id: 8,
    bookTitle: 'Pedro Páramo',
    authors: 'Juan Rulfo',
    description: { publishedYear: 1955 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=8",
    availabilityStatus: 'Exchange',
    price: 180,
  },
  {
    id: 9,
    bookTitle: 'La ciudad y los perros',
    authors: 'Mario Vargas Llosa',
    description: { publishedYear: 1963 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=9",
    availabilityStatus: 'For sale',
    price: 260,
  },
  {
    id: 10,
    bookTitle: 'La tregua',
    authors: 'Mario Benedetti',
    description: { publishedYear: 1960 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=10",
    availabilityStatus: 'Exchange',
    price: 190,
  },
  {
    id: 11,
    bookTitle: 'El túnel',
    authors: 'Ernesto Sabato',
    description: { publishedYear: 1948 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=11",
    availabilityStatus: 'Exchange',
    price: 210,
  },
  {
    id: 12,
    bookTitle: 'Fervor de Buenos Aires',
    authors: 'Jorge Luis Borges',
    description: { publishedYear: 1923 },
    gender: 'Poesía',
    image: "https://picsum.photos/300/300?random=12",
    availabilityStatus: 'For sale',
    price: 230,
  },
  {
    id: 13,
    bookTitle: 'Los detectives salvajes',
    authors: 'Roberto Bolaño',
    description: { publishedYear: 1998 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=13",
    availabilityStatus: 'Exchange',
    price: 320,
  },
  {
    id: 14,
    bookTitle: 'El Aleph',
    authors: 'Jorge Luis Borges',
    description: { publishedYear: 1949 },
    gender: 'Cuento',
    image: "https://picsum.photos/300/300?random=14",
    availabilityStatus: 'Exchange',
    price: 240,
  },
  {
    id: 15,
    bookTitle: 'Sobre héroes y tumbas',
    authors: 'Ernesto Sabato',
    description: { publishedYear: 1961 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=15",
    availabilityStatus: 'For sale',
    price: 290,
  },
  {
    id: 16,
    bookTitle: 'El otoño del patriarca',
    authors: 'Gabriel García Márquez',
    description: { publishedYear: 1975 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=16",
    availabilityStatus: 'Exchange',
    price: 310,
  },
  {
    id: 17,
    bookTitle: 'La guerra del fin del mundo',
    authors: 'Mario Vargas Llosa',
    description: { publishedYear: 1981 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=17",
    availabilityStatus: 'Exchange',
    price: 270,
  },
  {
    id: 18,
    bookTitle: 'El laberinto de la soledad',
    authors: 'Octavio Paz',
    description: { publishedYear: 1950 },
    gender: 'Ensayo',
    image: "https://picsum.photos/300/300?random=18",
    availabilityStatus: 'For sale',
    price: 250,
  },
  {
    id: 19,
    bookTitle: 'La región más transparente',
    authors: 'Carlos Fuentes',
    description: { publishedYear: 1958 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=19",
    availabilityStatus: 'Exchange',
    price: 260,
  },
  {
    id: 20,
    bookTitle: 'La casa verde',
    authors: 'Mario Vargas Llosa',
    description: { publishedYear: 1966 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=20",
    availabilityStatus: 'Exchange',
    price: 300,
  },
  {
    id: 21,
    bookTitle: 'Los recuerdos del porvenir',
    authors: 'Elena Garro',
    description: { publishedYear: 1963 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=21",
    availabilityStatus: 'Exchange',
    price: 270,
  },
  {
    id: 22,
    bookTitle: 'El reino de este mundo',
    authors: 'Alejo Carpentier',
    description: { publishedYear: 1949 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=22",
    availabilityStatus: 'For sale',
    price: 290,
  },
  {
    id: 23,
    bookTitle: 'Aura',
    authors: 'Carlos Fuentes',
    description: { publishedYear: 1962 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=23",
    availabilityStatus: 'Exchange',
    price: 240,
  },
  {
    id: 24,
    bookTitle: 'El Señor Presidente',
    authors: 'Miguel Ángel Asturias',
    description: { publishedYear: 1946 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=24",
    availabilityStatus: 'Exchange',
    price: 280,
  },
  {
    id: 25,
    bookTitle: 'Hijo de hombre',
    authors: 'Augusto Roa Bastos',
    description: { publishedYear: 1960 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=25",
    availabilityStatus: 'For sale',
    price: 220,
  },
  {
    id: 26,
    bookTitle: 'El astillero',
    authors: 'Juan Carlos Onetti',
    description: { publishedYear: 1961 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=26",
    availabilityStatus: 'Exchange',
    price: 230,
  },
  {
    id: 27,
    bookTitle: 'La muerte de Artemio Cruz',
    authors: 'Carlos Fuentes',
    description: { publishedYear: 1962 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=27",
    availabilityStatus: 'For sale',
    price: 260,
  },
  {
    id: 28,
    bookTitle: 'Los pasos perdidos',
    authors: 'Alejo Carpentier',
    description: { publishedYear: 1953 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=28",
    availabilityStatus: 'Exchange',
    price: 210,
  },
  {
    id: 29,
    bookTitle: 'De sobremesa',
    authors: 'José Asunción Silva',
    description: { publishedYear: 1925 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=29",
    availabilityStatus: 'For sale',
    price: 200,
  },
  {
    id: 30,
    bookTitle: 'El siglo de las luces',
    authors: 'Alejo Carpentier',
    description: { publishedYear: 1962 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=30",
    availabilityStatus: 'Exchange',
    price: 250,
  },
  {
    id: 31,
    bookTitle: 'Zama',
    authors: 'Antonio Di Benedetto',
    description: { publishedYear: 1956 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=31",
    availabilityStatus: 'Exchange',
    price: 270,
  },
  {
    id: 32,
    bookTitle: 'El obsceno pájaro de la noche',
    authors: 'José Donoso',
    description: { publishedYear: 1970 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=32",
    availabilityStatus: 'For sale',
    price: 260,
  },
  {
    id: 33,
    bookTitle: 'Balún Canán',
    authors: 'Rosario Castellanos',
    description: { publishedYear: 1957 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=33",
    availabilityStatus: 'Exchange',
    price: 230,
  },
  {
    id: 34,
    bookTitle: 'El libro vacío',
    authors: 'Josefina Vicens',
    description: { publishedYear: 1958 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=34",
    availabilityStatus: 'Exchange',
    price: 240,
  },
  {
    id: 35,
    bookTitle: 'Santa',
    authors: 'Federico Gamboa',
    description: { publishedYear: 1903 },
    gender: 'Novela',
    image: "https://picsum.photos/300/300?random=35",
    availabilityStatus: 'For sale',
    price: 250,
  },
];

  