name: Testing units test

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version: 18
            
      - name: Install Dependencies
        run: npm i

      - name: Run Test
        run: npm test
